#!/usr/bin/env kubectl apply -f
apiVersion: v1
kind: ConfigMap
metadata:
  name: om-director-data
data:
  director_config.yaml: |
    logging:
      format: text
      level: debug
      source: false

    debug:
      maxSends: 0
      maxMatchesPerSend: 0
      sleepBetweenSendsSeconds: 30

    agones:
      namespace: default
      fleetName: fps-sample-server
      generateName: fps-sample-server-

    api:
      functions:
        hostname: om-function
        grpcport: 50502

  ###

  profile.json: |
    {
      "name": "1v1",
      "pools": [
        {
          "name": "Everyone",
          "float_range_filters": [
            {
              "attribute": "mode.demo",
              "min": -100,
              "max": 100
            }
          ]
        }
      ]
    }